name: Build - latest

on:
  workflow_dispatch:
#  push:
#    branches: [ '*' ]
#    tags:
#      - v*
#  pull_request:
#   branches: [ master ]

jobs:
  build-docker:
    runs-on: ${{ matrix.os }}
    container: docker://hhmhh/ffmpeg_build:latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download deps
      run: |
        ${{ matrix.install-deps }}
        ./download.sh
      shell: bash

    - name: Build
      run: ./build.sh
      shell: bash

    - name: Debug
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: debug
        path: .

    - name: Package
      run: zip -r Linux.zip dist
      shell: bash

    - name: Publish
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
          files: Linux.zip
          draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest]
        include:
        - os: macOS-latest
          install-deps: |
             brew install nasm
          package-cmd: zip -r macOS.zip dist
          package-file: macOS.zip
        - os: windows-latest
          install-deps: |
             curl -LO https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip
             7z x nasm-2.15.05-win64.zip
             cp nasm-2.15.05/nasm.exe /usr/bin/nasm.exe
             rm /usr/bin/link.exe
          package-cmd: 7z a Windows.zip dist
          package-file: Windows.zip
    steps:
    - uses: actions/checkout@v2

    - name: Download deps
      run: |
        ${{ matrix.install-deps }}
        ./download.sh
      shell: bash

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: ./build.sh
      shell: bash

    - name: Debug
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: debug
        path: .

    - name: Package
      run: ${{ matrix.package-cmd }}
      shell: bash

    - name: Publish
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ matrix.package-file }}
          draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
