name: Build - latest

on:
  workflow_dispatch:
#  push:
#    branches: [ '*' ]
#    tags:
#      - v*
#  pull_request:
#   branches: [ master ]

jobs:
  build-docker:
    runs-on: ${{ matrix.job.os }}
    container: docker://hhmhh/ffmpeg_build:latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
                name: Linux,
                os: ubuntu-latest,
                target: x86_64-unknown-linux-gnu,
            }
          - { name: Windows,
              os: ubuntu-latest,
              target: x86_64-w64-mingw32,
            }

    steps:
    - uses: actions/checkout@v2

    - name: Download deps
      run: |
        ${{ matrix.install-deps }}
        ./download.sh
      shell: bash

    - name: Build
      run: ./build.sh ${{ matrix.job.target }}
      shell: bash

    - name: Debug
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: debug
        path: .

    - name: Package
      run: zip -r ${{ matrix.job.name }}.zip dist
      shell: bash

    - name: Publish
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
          files: ${{ matrix.job.name }}.zip
          draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: macOS-latest
        include:
        - os: macOS-latest
          install-deps: |
             brew install nasm
          package-cmd: zip -r macOS.zip dist
          package-file: macOS.zip
    steps:
    - uses: actions/checkout@v2

    - name: Download deps
      run: |
        ${{ matrix.install-deps }}
        ./download.sh
      shell: bash

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: ./build.sh
      shell: bash

    - name: Debug
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: debug
        path: .

    - name: Package
      run: ${{ matrix.package-cmd }}
      shell: bash

    - name: Publish
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ matrix.package-file }}
          draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
